name: CI

permissions: {}

on:
  push:
    branches-ignore:
      # these branches always have another event associated
      - gh-readonly-queue/**        # GitHub's merge queue uses `merge_group`
      - autodeps/**                 # autodeps always makes a PR
      - pre-commit-ci-update-config # pre-commit.ci's updates always have a PR
  pull_request:
  merge_group:

jobs:
  Windows:
    name: 'Windows (${{ matrix.python }}, ${{ matrix.arch }}${{ matrix.extra_name }})'

    timeout-minutes: 20
    runs-on: 'windows-latest'
    strategy:
      fail-fast: false
      matrix:
        python: ['3.14t']
        arch: ['x64']
        lsp: ['']
        lsp_extract_file: ['']
        extra_name: ['']

        # repeat everything 256x
        blah: ['1', '2', '3', '4']  # 4
        blahh: ['1', '2', '3', '4']  # 16
        blahhh: ['1', '2', '3', '4']  # 64
        blahhhh: ['1', '2', '3', '4']  # 256

    steps:
      - name: Grab the source from Git
        uses: actions/checkout@v5
        with:
          persist-credentials: false
      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: '${{ matrix.python }}'
          architecture: '${{ matrix.arch }}'
          allow-prereleases: true
      - name: Run tests
        run: ./ci.sh
        shell: bash
        env:
          LSP: '${{ matrix.lsp }}'
          LSP_EXTRACT_FILE: '${{ matrix.lsp_extract_file }}'
